config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  # namespace :customer do
  #   resources :reservations, only: [:index]
  # end

  # resources :tables
  resources :restaurants do
    resources :tables
  end
  # get 'customer/home'
  # get 'owner/home'
  # get 'admin/home'
  devise_for :users
  root 'tablelinks#home'
  #Customer Routes
  get 'customer/home', to: 'customer#home', as: 'customer_home'
  get 'customer/viewreservations', to: 'customer#viewreservations', as: 'customer_viewreservations'

  #Owner Routes
  get 'owner/home', to: 'owner#home', as: 'owner_home'
  get 'owner/viewreservations', to: 'owner#viewreservations', as: 'owner_viewreservations'
  get 'owner/viewrestaurants', to: 'owner#viewrestaurants', as: 'owner_viewrestaurants'

  #Admin Routes
  get 'admin/home', to: 'admin#home', as: 'admin_home'
  get 'admin/index', to: 'admin#index', as: 'admin_index'

  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to table_url(@table), notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to table_url(@table), notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy!

    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:table_name, :seat_numbers)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table) do |form| %>
  <% if table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :table_name, style: "display: block" %>
    <%= form.text_field :table_name %>
  </div>

  <div>
    <%= form.label :seat_numbers, style: "display: block" %>
    <%= form.number_field :seat_numbers %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <strong>Table name:</strong>
    <%= table.table_name %>
  </p>

  <p>
    <strong>Seat numbers:</strong>
    <%= table.seat_numbers %>
  </p>

</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", @table %> |
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tables</h1>

<div id="tables">
  <% @tables.each do |table| %>
    <%= render table %>
    <p>
      <%= link_to "Show this table", table %>
    </p>
  <% end %>
</div>

<%= link_to "New table", new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<div>
  <%= link_to "Edit this table", edit_table_path(@table) %> |
  <%= link_to "Back to tables", tables_path %>

  <%= button_to "Destroy this table", @table, method: :delete %>
</div>