config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  # namespace :customer do
  #   resources :reservations, only: [:index]
  # end

  # resources :tables
  resources :restaurants do
    resources :tables
  end
  # get 'customer/home'
  # get 'owner/home'
  # get 'admin/home'
  devise_for :users
  root 'tablelinks#home'
  #Customer Routes
  get 'customer/home', to: 'customer#home', as: 'customer_home'
  get 'customer/viewreservations', to: 'customer#viewreservations', as: 'customer_viewreservations'

  #Owner Routes
  get 'owner/home', to: 'owner#home', as: 'owner_home'
  get 'owner/viewreservations', to: 'owner#viewreservations', as: 'owner_viewreservations'
  get 'owner/viewrestaurants', to: 'owner#viewrestaurants', as: 'owner_viewrestaurants'

  #Admin Routes
  get 'admin/home', to: 'admin#home', as: 'admin_home'
  get 'admin/index', to: 'admin#index', as: 'admin_index'

  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to 'TableLinks', root_path, class: "navbar-brand" %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', data: { turbo_method: :delete } %>
          </li>
          <% if current_user.role == 'Admin' %>
            <li class="nav-item">
              <%= link_to "View All Data", admin_index_path, class: "nav-link" %>
            </li>
          <% elsif current_user.role == 'Owner' %>
          <!-- Create Restaurant -->
          <li class="nav-item">
            <%= link_to "Create Restaurant", new_restaurant_table_path, class: "nav-link" %>
          </li>
          <!-- View All their Restaurants (only theirs) -->
          <li class="nav-item">
            <%= link_to "View Restaurants", owner_viewrestaurants_path, class: "nav-link" %>
          </li>
          <!-- View All Reservations for their Restaurants -->
          <li class="nav-item">
            <%= link_to "View Reservations", owner_viewreservations_path, class: "nav-link" %>
          </li>
          <% elsif current_user.role == 'Customer' %>
          <!-- Create Reservations -->
          <li class="nav-item">
            <%= link_to "Create Reservations", new_reservation_path, class: "nav-link" %>
          </li>
          <!-- View all thier Reservations -->
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign-Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign-In", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %> <!-- This is the missing end tag -->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Tablelinks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

   

  </head>
  <body>
    <%= render 'layouts/header'%>
    
    <div class="container"> 
      <br/>
        <% if notice%>
          <%= render 'layouts/alerts'%>
        <% end %>
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>